config/routes.rb
Rails.application.routes.draw do
 
  root 'categories#index'

  resources :categories do
    resources :items
  end

  scope 'items/:item_id', as: 'item' do 
    resources :ratings, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  has_many :ratings, dependent: :destroy
end

app/models/rating.rb
class Rating < ApplicationRecord
  before_save :check_author
  belongs_to :item

  def check_author
    if self.author.blank?
      self.author = 'anon'
    end 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_cat, only: [:show, :update, :edit, :destroy] 


  def index
    @categories = Category.all
  end

  def show
  end
  
  def new
    @category = Category.new
    render :form
  end

  def edit
    render :form
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def update 
    if @category.update(category_params)
      redirect_to @category
    else 
      render :edit
    end
  end

  def destroy 
    @category.destroy
    redirect_to categories_path
  end


    private

    def set_cat
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_category
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def index
    @items = @category.items
  end

  def show
    # binding.pry
    # @rating = Rating.all
  end

  def new
    @item = @category.items.new
    render :form
  end

  def edit
    render :form
  end

  def create 
    @item = @category.items.create(item_params)

    if @item.save
      redirect_to [@category, @item]
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to [@category, @item]
    else
      render :edit
    end
  end

  def destroy
    @item.destroy 
    redirect_to category_items_path
  end 


    private

    def set_category
      @category = Category.find(params[:category_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :price, :available)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_item

  def new
    @rating = @item.ratings.new
  end

  def create
    @rating = @item.ratings.new(rating_params)
    if @rating.save
      redirect_to category_item_path(@item.category_id, @item)
    else 
      render :new
    end
  end

    private
    def set_item
      @item = Item.find(params[:item_id])
    end

    def rating_params
      params.require(:rating).permit(:body, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/categories/_form.html.erb
<h1><%= @category.id ? 'Edit Department' : 'Create Department' %></h1>

<% form_for @category do |f| %>

  <%= f.label :name %>
  <%= f.text_area :name, required: true, autofocus: true %>

  <%= f.submit %>

<% end %>

app/views/categories/edit.html.erb
<h1>Categorys#edit</h1>
<p>Find me in app/views/categorys/edit.html.erb</p>

app/views/categories/form.html.erb
<h1><%= @category.id ? 'Edit Department' : 'Create Department' %></h1>

<%= form_for @category do |f| %>

  <%= f.label :name %>
  <%= f.text_area :name, required: true, autofocus: true %>

  <%= f.submit %>

<% end %>

app/views/categories/index.html.erb
<h1>Deparment Store</h1>
<p>Click on a deparment below to see inventory</p>
<%= link_to 'Add a Department', new_category_path %>

<% @categories.each do |category| %>
<ul>
  <li>
    <%= link_to category.name, category_items_path(category.id) %>
  </li>
</ul>
<% end %>

app/views/categories/new.html.erb
<h1>Categorys#new</h1>
<p>Find me in app/views/categorys/new.html.erb</p>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<hr />
<h3>What deparment would you like to do?</h3>
<%= link_to 'View Inventory', category_items_path%>
<%= link_to 'Edit Department', edit_category_path %>
<%= link_to 'Delete Department', @category, method: :delete %>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@category, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.submit %>
  
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@category, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_area :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.submit %>
  
<% end %>

app/views/items/index.html.erb
<h1><%= @category.name %></h1>
<%= link_to 'Create a new item', new_category_item_path(@category) %>

<% @items.each do |item| %>
<ul>

  <li><%= link_to item.name, [@category, item] %></li>
</ul>
<% end %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @category.name %> - <%= @item.name %></h1>
<hr />
<p><%= @item.description %></p>
<h4>Price: $<%= @item.price %></h4>

<% @item.ratings.each do |rating| %>
  <%= render 'ratings/rating', { rating: rating } %>
<% end %>

<hr />
<%= link_to 'Edit Item', edit_category_item_path(@category, @item) %>
<%= link_to 'Delete Item', category_item_path(@category, @item), method: :delete %>
<%= link_to 'Add Comment', new_item_rating_path(@item) %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Department</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/ratings/_rating.html.erb
<hr />
<p>Author: <%= rating.author %></p>
<br />
<p>Comment: <%= rating.body %></p>
<hr />

app/views/ratings/new.html.erb
<h1>Add a Reveiw</h1>
<%= form_for [@item, @rating] do |f| %>
  <%= f.label :body %>
  <br/ >
  <strong><%= f.text_field :body %></strong>
  <br />
  <br />

  <%= f.label :author %>
  <br />
  <%= f.text_area :author, placeholder: 'Name' %>
  <br />
  <%= f.submit %>
<% end %>